export const PROFESSIONS = [
  "Accountant",
  "Actor",
  "Architect",
  "Artist",
  "Baker",
  "Banker",
  "Barista",
  "Bartender",
  "Biologist",
  "Business Analyst",
  "Chef",
  "Civil Engineer",
  "Content Creator",
  "Copywriter",
  "Data Scientist",
  "Dentist",
  "Designer",
  "Doctor",
  "Driver",
  "Economist",
  "Editor",
  "Electrician",
  "Engineer",
  "Entrepreneur",
  "Fashion Designer",
  "Filmmaker",
  "Financial Advisor",
  "Fitness Trainer",
  "Graphic Designer",
  "Hairdresser",
  "Hotel Manager",
  "HR Manager",
  "Illustrator",
  "Influencer",
  "Interior Designer",
  "Journalist",
  "Lawyer",
  "Librarian",
  "Marketing Manager",
  "Mechanical Engineer",
  "Musician",
  "Nurse",
  "Nutritionist",
  "Pharmacist",
  "Photographer",
  "Pilot",
  "Plumber",
  "Police Officer",
  "Product Manager",
  "Professor",
  "Psychologist",
  "Real Estate Agent",
  "Receptionist",
  "Researcher",
  "Sales Representative",
  "Scientist",
  "Software Developer",
  "Software Engineer",
  "Student",
  "Teacher",
  "Technician",
  "Tour Guide",
  "Translator",
  "UX/UI Designer",
  "Veterinarian",
  "Video Editor",
  "Waiter",
  "Writer",
  "Yoga Instructor"
].sort();
